resource_types:
- name: google-cloud-storage
  type: registry-image
  source:
    repository: frodenas/gcs-resource
- name: file-url
  type: registry-image
  source:
    repository: pivotalservices/concourse-curl-resource
    tag: latest
- name: slack
  type: registry-image
  source:
    repository: arbourd/concourse-slack-alert-resource

config:
- &allIsPublic   true
- &imageRepo     gcr.io/cf-london-servces-k8s/kind-on-c/kind-on-c
- &baseImageRepo ubuntu
- &gitBotName    kind-on-c pipeline
- &gitBotEmail   hhorl+kindonc@pivotal.io
- k8s-branches:
  - &k8sBranchMaster        master
  - &k8sBranchCurrent       release-1.17
  - &k8sBranchCurrentMinus1 release-1.16
  - &k8sBranchCurrentMinus2 release-1.15
- &imageBuildingFiles
  - Dockerfile
- &kindOnCGitSource
  uri: git@github.com:pivotal-k8s/kind-on-c
  branch: dev
  private_key: ((github.push_key))
  git_config:
  - name: user.name
    value: *gitBotName
  - name: user.email
    value: *gitBotEmail
- &testTask
  task: run-tests
  file: kind-on-c/kind.yaml
  privileged: true
  params:
    KIND_TESTS: |
      set -x
      kubectl get nodes -o wide
      kubectl get all --all-namespaces
      kubectl run test --rm=true --image=busybox -i --wait=true --restart=Never --command -- \
        echo 'The pod says: the kubernetes cluster sure works!'
- &bashTaskConf
  platform: linux
  image_resource:
    type: registry-image
    source:
      repository: bash
- &golangTaskConf
  platform: linux
  image_resource:
    type: registry-image
    source:
      repository: "golang"
- &notify
  on_success:
    put: success message
    resource: slack
    params:
      alert_type: fixed
  on_failure:
    put: failure message
    resource: slack
    params:
      alert_type: broke
  on_error:
    put: error message
    resource: slack
    params:
      alert_type: broke
- &jobDefaults
  public: *allIsPublic
  serial: true
  <<: *notify
- &resourceDefaults
  public: *allIsPublic
# To safe some cpu cycles:
- &noCheck
  # virtually disable checking of the resource
  check_every: "8760h"
- &slowCheck
  # for resources we don't trigger on and it does not matter too much if we get
  # the most recent version
  check_every: "20m"

resources:
- name: base-image
  <<: *resourceDefaults
  type: registry-image
  icon: layers-triple-outline
  source:
    repository: *baseImageRepo
- name: image
  <<: *resourceDefaults
  type: registry-image
  icon: layers-triple
  source:
    repository: *imageRepo
    username: ((registry.username))
    password: ((registry.password))
    tag: ci-latest
- name: kind-build
  <<: *resourceDefaults
  type: google-cloud-storage
  icon: application-export
  source:
    bucket: kind-on-c-pipeline
    json_key: ((bucket.key))
    versioned_file: "pipeline-builds/kind-linux-amd64"
- name: dockerfile
  <<: *resourceDefaults
  type: git
  icon: docker
  source:
    << : *kindOnCGitSource
    paths: *imageBuildingFiles
- name: kind-on-c-dev
  <<: *resourceDefaults
  type: git
  icon: source-branch
  source:
    << : *kindOnCGitSource
    ignore_paths: *imageBuildingFiles
- name: kind-on-c-master
  <<: *resourceDefaults
  type: git
  icon: source-merge
  source:
    << : *kindOnCGitSource
    branch: master
  <<: *noCheck
- name: kind-release
  <<: *resourceDefaults
  type: github-release
  icon: application-import
  source:
    owner: kubernetes-sigs
    repository: kind
    access_token: ((github.token))
    pre_release: true
- name: kind-git-master
  <<: *resourceDefaults
  type: git
  icon: source-fork
  source:
    uri: https://github.com/kubernetes-sigs/kind
    branch: master
- name: k8s-git-current-minus-2
  <<: *resourceDefaults
  type: git
  icon: kubernetes
  source:
    uri: https://github.com/kubernetes/kubernetes
    branch: *k8sBranchCurrentMinus2
  <<: *slowCheck
- name: k8s-git-current-minus-1
  <<: *resourceDefaults
  type: git
  icon: kubernetes
  source:
    uri: https://github.com/kubernetes/kubernetes
    branch: *k8sBranchCurrentMinus1
  <<: *slowCheck
- name: k8s-git-current
  <<: *resourceDefaults
  type: git
  icon: kubernetes
  source:
    uri: https://github.com/kubernetes/kubernetes
    branch: *k8sBranchCurrent
  <<: *slowCheck
- name: k8s-git-master
  <<: *resourceDefaults
  type: git
  icon: kubernetes
  source:
    uri: https://github.com/kubernetes/kubernetes
    branch: *k8sBranchMaster
  <<: *slowCheck
- name: container-diff-bin
  <<: *resourceDefaults
  type: file-url
  icon: vector-difference
  source:
    url: https://storage.googleapis.com/container-diff/latest/container-diff-linux-amd64
    filename: container-diff
  <<: *slowCheck
- name: slack
  <<: *resourceDefaults
  type: slack
  icon: chat-processing
  source:
    url: ((slack.url))
  <<: *noCheck

jobs:
- name: update image
  <<: *jobDefaults
  on_success:
    put: success message
    resource: slack
    params:
      alert_type: success
      message: New kind-on-c image pushed and promoted
  plan:
  - in_parallel:
      fail_fast: true
      steps:
      - get: base-image
        trigger: true
      - get: dockerfile
        trigger: true
      - get: kind-on-c-dev
      - get: container-diff-bin
  - task: build
    privileged: true
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: vito/oci-build-task
      params:
        CONTEXT: dockerfile
        BASE_IMAGE_REPO: *baseImageRepo
        UNPACK_ROOTFS: true
      inputs:
      - name: base-image
      - name: dockerfile
      outputs:
      - name: image
      caches:
      - path: cache
      run:
        path: sh
        args:
        - -euc
        - |
          set -o pipefail

          kind_on_c_ver="$( git --git-dir=dockerfile/.git describe --always --tags )"
          base_img_ver="$( cat base-image/digest )"

          cat <<EOF > image/build_args
          KIND_ON_C_VERSION=${kind_on_c_ver}
          BASE_IMAGE=${BASE_IMAGE_REPO}@${base_img_ver}
          EOF

          BUILD_ARGS_FILE=image/build_args build
  - put: image-push
    resource: image
    params:
      image: image/image.tar
    inputs:
    - image
  # - task: test new image ## TODO
  - task: update image revision
    image: image # use image from the builder task
    config:
      platform: linux
      params:
        GIT_AUTHOR_NAME:  *gitBotName
        GIT_AUTHOR_EMAIL: *gitBotEmail
      inputs:
      - name: image-push
      - name: image
      - name: kind-on-c-dev
      - path: bin
        name: container-diff-bin
      outputs:
      - name: kind-on-c-dev
      caches:
      - path: cache
      run:
        path: bash
        args:
        - -euc
        - |
          set -o pipefail

          taskConf="${PWD}/kind-on-c-dev/kind.yaml"
          tmpDir="$(mktemp -d)"
          trap 'rm -rf -- "$tmpDir"' EXIT

          chmod 0750 bin/container-diff
          export PATH="${PATH}:${PWD}/bin"

          c0Repo="$( yq -r '.image_resource.source.repository' "$taskConf" )"
          c0Digest="$( yq -r '.image_resource.version.digest' "$taskConf" )"
          c1Digest="$( cat "image-push/digest" )"

          c0="remote://${c0Repo}@${c0Digest}"
          c1="${PWD}/image/image.tar"

          diffCmd=(
            container-diff diff "$c0" "$c1"
              --type pip --type apt --type file --type size --type history
              --cache-dir "${PWD}/cache" --verbosity info
          )

          tmpGitMsg="${tmpDir}/git_messages.txt"
          tmpTaskConf="${tmpDir}/task.yml"

          yq -y --arg d "${c1Digest}" '.image_resource.version.digest = $d' "$taskConf" > "$tmpTaskConf"
          cat "$tmpTaskConf" > "$taskConf"

          cd kind-on-c-dev

          git config --global user.email "$GIT_AUTHOR_EMAIL"
          git config --global user.name "$GIT_AUTHOR_NAME"

          git add "$taskConf"
          git diff --quiet && git diff --staged --quiet || {
            printf \
              'Update container image to "%s"\n\n----\n\nCommand:\n```\n%s\n```\nContainer Diff:\n```\n%s\n```\n' \
              "${c1Digest}" \
              "${diffCmd[*]}" \
              "$( "${diffCmd[@]}" )" \
              > "$tmpGitMsg"

            git commit --quiet --file "$tmpGitMsg"
            git show -1 | cat
          }
  - put: kind-on-c-dev
    params:
      repository: kind-on-c-dev
      rebase: true

- name: latest kind release
  <<: *jobDefaults
  plan:
  - in_parallel: &commonTestInputsForKindRelease
    - get: kind-on-c
      resource: kind-on-c-dev
      trigger: true
      passed: &allFeatureTests
      - custom kind config
      - HA control plane
      - output node image & rootfs
      - user inputs & outputs
      - MetalLB & exposed services
    - get: kind-release
      trigger: true
      params:
        globs:
        - kind-linux-amd64
      passed: *allFeatureTests
  - *testTask
- name: latest kind release with k8s-master
  <<: *jobDefaults
  plan:
  - in_parallel:
    - in_parallel: *commonTestInputsForKindRelease
    - get: k8s-git
      resource: k8s-git-master
  - << : *testTask
- name: latest kind release with k8s-current
  <<: *jobDefaults
  plan:
  - in_parallel:
    - in_parallel: *commonTestInputsForKindRelease
    - get: k8s-git
      resource: k8s-git-current
  - << : *testTask
- name: latest kind release with k8s-current-minus-1
  <<: *jobDefaults
  plan:
  - in_parallel:
    - in_parallel: *commonTestInputsForKindRelease
    - get: k8s-git
      resource: k8s-git-current-minus-1
  - << : *testTask
- name: latest kind release with k8s-current-minus-2
  <<: *jobDefaults
  plan:
  - in_parallel:
    - in_parallel: *commonTestInputsForKindRelease
    - get: k8s-git
      resource: k8s-git-current-minus-2
  - << : *testTask

- name: promote
  <<: *jobDefaults
  on_success:
    put: success message
    resource: slack
    params:
      alert_type: success
      message: New kind-on-c promoted from dev to master
  plan:
  - get: kind-on-c-dev
    trigger: true
    passed:
    # all tests for the kind release
    - latest kind release
    - latest kind release with k8s-master
    - latest kind release with k8s-current
    - latest kind release with k8s-current-minus-1
    - latest kind release with k8s-current-minus-2
    # all tests for kind master
    - kind master
    - kind master with k8s-current-minus-2
    - kind master with k8s-current-minus-1
    - kind master with k8s-current
    - kind master with k8s-master
  - put: kind-on-c-master
    params:
      repository: kind-on-c-dev

- name: build kind from master
  <<: *jobDefaults
  plan:
  - get: kind-git-master
    trigger: true
  - task: build
    config:
      << : *golangTaskConf
      inputs:
      - name: kind-git-master
        path: src
      outputs:
      - name: kind-bin
      params:
        CGO_ENABLED: 0
        GO111MODULE: "on"
      run:
        path: bash
        args:
        - -euc
        - |
          cd ./src
          go get -d ./...
          go build main.go

          mv main "../kind-bin/kind-linux-amd64"

          ls -l ../kind-bin/
  - put: kind-build
    params:
      file: kind-bin/kind-linux-amd64

- name: kind master
  <<: *jobDefaults
  plan:
  - in_parallel: &commonTestInputsForKindMaster
    - get: kind-on-c
      resource: kind-on-c-dev
      trigger: true
      passed: *allFeatureTests
    - get: kind-release
      passed: [ build kind from master ]
      resource: kind-build
      trigger: true
  - *testTask
- name: kind master with k8s-current-minus-2
  <<: *jobDefaults
  plan:
  - in_parallel:
    - in_parallel: *commonTestInputsForKindMaster
    - get: k8s-git
      resource: k8s-git-current-minus-2
  - << : *testTask
- name: kind master with k8s-current-minus-1
  <<: *jobDefaults
  plan:
  - in_parallel:
    - in_parallel: *commonTestInputsForKindMaster
    - get: k8s-git
      resource: k8s-git-current-minus-1
  - << : *testTask
- name: kind master with k8s-current
  <<: *jobDefaults
  plan:
  - in_parallel:
    - in_parallel: *commonTestInputsForKindMaster
    - get: k8s-git
      resource: k8s-git-current
  - << : *testTask
- name: kind master with k8s-master
  <<: *jobDefaults
  plan:
  - in_parallel:
    - in_parallel: *commonTestInputsForKindMaster
    - get: k8s-git
      resource: k8s-git-master
  - << : *testTask

# additional "feature" tests
- name: HA control plane
  <<: *jobDefaults
  plan:
  - in_parallel: &commonTestInputsForFeatures
    - get: kind-on-c
      resource: kind-on-c-dev
      trigger: true
    - get: kind-release
      trigger: true
      params:
        globs:
        - kind-linux-amd64
  - << : *testTask
    params:
      KIND_CONFIG: |
        kind: Cluster
        apiVersion: kind.sigs.k8s.io/v1alpha3
        nodes:
        - role: control-plane
        - role: control-plane
        - role: control-plane
      KIND_TESTS: |
        set -x

        . kind-on-c/lib.inc.sh

        expectedNrOfNodes=3      # 0 worker + 3 control plane nodes
        expectedNrOfContainers=4 # 0 worker + 3 control plane + 1 loadbalancer

        actualNrOfContainers=$( kind get nodes | wc -l )
        [[ $expectedNrOfContainers -eq $actualNrOfContainers ]] || {
          log::error "Expectd to find ${expectedNrOfContainers} kind nodes, found ${actualNrOfContainers}"
          exit 1
        }

        actualNrOfNodes=$( kubectl get nodes --no-headers | wc -l )
        [[ $expectedNrOfNodes -eq $actualNrOfNodes ]] || {
          log::error "Expectd to find ${expectedNrOfNodes} kubernetes nodes, found ${actualNrOfNodes}"
          exit 2
        }
- name: custom kind config
  <<: *jobDefaults
  plan:
  - in_parallel: *commonTestInputsForFeatures
  - << : *testTask
    params:
      KIND_CONFIG: |
        kind: Cluster
        apiVersion: kind.sigs.k8s.io/v1alpha3
        nodes:
        - role: control-plane
        - role: worker
      KIND_TESTS: |
        set -x
        . kind-on-c/lib.inc.sh
        nrOfNodes=$( kubectl get nodes --no-headers | wc -l )
        [[ $nrOfNodes -eq 2 ]] || {
          log::error "Expectd 2 nodes, found $nrOfNodes"
          exit 1
        }
- name: output node image & rootfs
  <<: *jobDefaults
  plan:
  - in_parallel:
    - in_parallel: *commonTestInputsForFeatures
    - get: k8s-git
      resource: k8s-git-current-minus-1
  - << : *testTask
    task: export node image
    params:
      EXPORT_NODE_IMAGE: 1
      EXPORT_NODE_ROOTFS: 1
      KIND_TESTS: '' # skip bringing up the cluster, only create the image
  - task: run rootfs
    image: exported-node-rootfs # the rootfs of the node image built by kind, from the previous task
    config:
      platform: linux
      inputs:
      - name: exported-node-image
      - name: kind-on-c
      run:
        path: bash
        args:
        - -xeuc
        - |
          . kind-on-c/lib.inc.sh
          expImg='exported-node-image/image.tar'
          test -e "$expImg" || {
            log::error "'${expImg}' not found. What's with that\!?"
            exit 1
          }
  - << : *testTask
    task: run-tests with previously exported node image
    input_mapping:
      node-image: exported-node-image
    params:
      EXPECTED_BRANCH: *k8sBranchCurrentMinus1
      KIND_CONFIG: |
        kind: Cluster
        apiVersion: kind.sigs.k8s.io/v1alpha3
        nodes:
        - role: control-plane
      KIND_TESTS: |
        set -x
        . kind-on-c/lib.inc.sh

        # convert the branch name 'release-1.15' to 'v1.15.' which can be used
        # as part of a glob for the version comparison
        expectedVer="v${EXPECTED_BRANCH/#release-}."
        actualVer="$( kubectl get nodes -o json | jq -r .items[0].status.nodeInfo.kubeletVersion )"
        [[ $actualVer == "$expectedVer"* ]] || {
          log::error "Expected APIServer to match version '${expectedVer}', got '${actualVer}'"
          exit 1
        }
- name: user inputs & outputs
  <<: *jobDefaults
  plan:
  - in_parallel:
    - in_parallel: *commonTestInputsForFeatures
    # those are just random inputs, to show how one could aggregate multiple
    # inputs and prepare them for kind-on-c
    - { get: input-1 , resource: dockerfile }
    - { get: input-2 , resource: dockerfile }
  - task: aggregate inputs
    config:
      << : *bashTaskConf
      inputs:
      - name: input-1
      - name: input-2
      outputs:
      - name: agg-inputs
      run:
        path: bash
        args:
        - -xeuc
        - |
          cp -a input-1 agg-inputs/
          cp -a input-2 agg-inputs/
  - << : *testTask
    task: use inputs & populate outputs
    params:
      KIND_PRE_START: |
        set -x
        cp -a inputs/input-1 outputs/eins
        cp -a inputs/input-2 outputs/zwei
    input_mapping:
      inputs: agg-inputs
  - task: check aggregated outputs
    config:
      << : *bashTaskConf
      inputs:
      - name: outputs
      - name: kind-on-c
      run:
        path: bash
        args:
        - -xeuc
        - |
          . kind-on-c/lib.inc.sh
          expectedOutputs=( outputs/eins outputs/zwei )
          for o in "${expectedOutputs[@]}"
          do
            [ -d "$o" ] || {
              log::error "expected output '$o' to exist"
              exit 1
            }
          done
- name: MetalLB & exposed services
  <<: *jobDefaults
  plan:
  - in_parallel: *commonTestInputsForFeatures
  - << : *testTask
    params:
      INSTALL_METALLB: 1
      KIND_TESTS: |
        set -x

        PORT=8080
        NAME='echo'
        IMG='inanimate/echo-server'

        kubectl run --generator=run-pod/v1 "$NAME" --image="$IMG" --port="$PORT"
        kubectl expose pod "$NAME" --type=LoadBalancer

        connectFromExt() {
          local extIP
          extIP="$( kubectl get service "$NAME" -o 'jsonpath={.status.loadBalancer.ingress[0].ip}' 2>/dev/null )"

          [ -n "$extIP" ] || return 1

          curl --silent --fail "http://${extIP}:${PORT}"
        }

        . kind-on-c/lib.inc.sh

        # try every 6 seconds, 20 times -> 2 minutes
        retry 20 6 connectFromExt

groups:
- name: all
  jobs:
  - promote
  - latest kind release
  - latest kind release with k8s-master
  - latest kind release with k8s-current
  - latest kind release with k8s-current-minus-1
  - latest kind release with k8s-current-minus-2
  - build kind from master
  - kind master
  - kind master with k8s-current-minus-2
  - kind master with k8s-current-minus-1
  - kind master with k8s-current
  - kind master with k8s-master
  - custom kind config
  - HA control plane
  - output node image & rootfs
  - user inputs & outputs
  - MetalLB & exposed services
- name: image
  jobs:
  - update image
- name: kind release
  jobs:
  - latest kind release
  - latest kind release with k8s-master
  - latest kind release with k8s-current
  - latest kind release with k8s-current-minus-1
  - latest kind release with k8s-current-minus-2
- name: kind master
  jobs:
  - build kind from master
  - kind master
  - kind master with k8s-current-minus-2
  - kind master with k8s-current-minus-1
  - kind master with k8s-current
  - kind master with k8s-master
- name: features
  jobs:
  - custom kind config
  - HA control plane
  - output node image & rootfs
  - user inputs & outputs
  - MetalLB & exposed services
- name: promote
  jobs:
  - promote
