resource_types:
- name: google-cloud-storage
  type: registry-image
  source:
    repository: frodenas/gcs-resource

resources:
- name: base-image
  type: registry-image
  source:
    repository: alpine
- name: image
  type: registry-image
  source:
    repository: gcr.io/cf-london-servces-k8s/kind-on-c/kind-on-c
    username: ((registry.username))
    password: ((registry.password))
- name: dev-image
  type: registry-image
  source:
    repository: gcr.io/cf-london-servces-k8s/kind-on-c/kind-on-c
    username: ((registry.username))
    password: ((registry.password))
    tag: ci-rc
- name: kind-build
  type: google-cloud-storage
  source:
    bucket: kind-on-c-pipeline
    json_key: ((bucket.key))
    versioned_file: "pipeline-builds/kind-linux-amd64"
- name: builder-task
  type: git
  source:
    uri: https://github.com/concourse/builder-task
- name: kind-on-c
  type: git
  source:
    uri: https://github.com/pivotal-k8s/kind-on-c
    branch: dev
- name: kind-on-c-master
  type: git
  source:
    uri: git@github.com:pivotal-k8s/kind-on-c
    branch: master
    private_key: ((github.push_key))
- name: kind-release
  type: github-release
  source:
    owner: kubernetes-sigs
    repository: kind
    access_token: ((github.token))
    pre_release: true
- name: kind-git-master
  type: git
  source:
    uri: https://github.com/kubernetes-sigs/kind
    branch: master
- name: k8s-git-1.13
  type: git
  source:
    uri: https://github.com/kubernetes/kubernetes
    branch: release-1.13
- name: k8s-git-1.14
  type: git
  source:
    uri: https://github.com/kubernetes/kubernetes
    branch: release-1.14
- name: k8s-git-1.15
  type: git
  source:
    uri: https://github.com/kubernetes/kubernetes
    branch: release-1.15
- name: k8s-git-master
  type: git
  source:
    uri: https://github.com/kubernetes/kubernetes
    branch: master

jobs:
- name: build dev-image
  plan:
  - in_parallel:
      fail_fast: true
      steps:
      - get: builder-task
      - get: base-image
        trigger: true
      - get: kind-on-c
        trigger: true
      - get: kind-release
        trigger: true
  - task: build
    privileged: true
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: concourse/builder-task
      params:
        REPOSITORY: gcr.io/cf-london-servces-k8s/kind-on-c/kind-on-c
        CONTEXT: kind-on-c
      inputs:
      - name: kind-release
      - name: base-image
      - name: builder-task
      - name: kind-on-c
      outputs:
      - name: image
      caches:
      - path: cache
      run:
        path: bash
        args:
        - -c
        - |
          tagParts=(
            "$( cut -d: -f2- base-image/digest )" # alpine / base image version
            "$( git --git-dir=kind-on-c/.git describe --always --tags )" # kind-on-c version
            "$( cat kind-release/commit_sha )" # kind version
          )
          export TAG="$( IFS='-'; echo "${tagParts[*]}" )"

          echo "$TAG" > image/additional_tags

          builder-task/build
  - put: push
    resource: dev-image
    params:
      image: image/image.tar
      additional_tags: image/additional_tags

- name: test
  plan:
  - in_parallel:
    - &fromDevImageBuild
      get: kind-on-c
      passed: [ build dev-image ]
      trigger: true
    - <<: *fromDevImageBuild
      get: dev-image
    - <<: *fromDevImageBuild
      get: kind-release
      params:
        globs:
        - kind-linux-amd64
  - &testTask
    task: run-tests
    file: kind-on-c/kind.yaml
    image: dev-image
    privileged: true
    params:
      KIND_TESTS: |
        set -eux
        kubectl get nodes -o wide
        kubectl get all --all-namespaces
        kubectl run test --rm=true --image=busybox -i --wait=true --restart=Never --command -- \
          echo 'The pod says: the kubernetes cluster sure works!'
- name: test with k8s-master
  plan:
  - in_parallel:
    - <<: *fromDevImageBuild
      get: kind-on-c
    - <<: *fromDevImageBuild
      get: dev-image
    - <<: *fromDevImageBuild
      get: kind-release
      params:
        globs:
        - kind-linux-amd64
    - get: k8s-git
      resource: k8s-git-master
  - << : *testTask
- name: test with k8s-1.15
  plan:
  - in_parallel:
    - <<: *fromDevImageBuild
      get: kind-on-c
    - <<: *fromDevImageBuild
      get: dev-image
    - <<: *fromDevImageBuild
      get: kind-release
      params:
        globs:
        - kind-linux-amd64
    - get: k8s-git
      resource: k8s-git-1.15
  - << : *testTask
- name: test with k8s-1.14
  plan:
  - in_parallel:
    - <<: *fromDevImageBuild
      get: kind-on-c
    - <<: *fromDevImageBuild
      get: dev-image
    - <<: *fromDevImageBuild
      get: kind-release
      params:
        globs:
        - kind-linux-amd64
    - get: k8s-git
      resource: k8s-git-1.14
  - << : *testTask
- name: test with k8s-1.13
  plan:
  - in_parallel:
    - <<: *fromDevImageBuild
      get: kind-on-c
    - <<: *fromDevImageBuild
      get: dev-image
    - <<: *fromDevImageBuild
      get: kind-release
      params:
        globs:
        - kind-linux-amd64
    - get: k8s-git
      resource: k8s-git-1.13
  - << : *testTask

- name: promote
  plan:
  - in_parallel:
    - get: dev-image
      trigger: true
      passed: &allTestJobs
      - test
      - test with k8s-master
      - test with k8s-1.15
      - test with k8s-1.14
      - test with k8s-1.13
      - test with kind-master
      - test with kind-master and k8s-1.13
      - test with kind-master and k8s-1.14
      - test with kind-master and k8s-1.15
      - test with kind-master and k8s-master
      params:
        format: oci
    - get: kind-on-c
      trigger: true
      passed: *allTestJobs
  - in_parallel:
    - put: kind-on-c-master
      params:
        repository: kind-on-c
    - put: promote
      resource: image
      params:
        image: dev-image/image.tar

- name: build kind from master
  plan:
  - get: kind-git-master
    trigger: true
  - task: build
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: "golang"
          tag: "1.12"
      inputs:
      - name: kind-git-master
        path: src
      outputs:
      - name: kind-bin
      params:
        CGO_ENABLED: 0
        GO111MODULE: "on"
      run:
        path: bash
        args:
        - -c
        - |
          set -e

          cd ./src
          go get -d ./...
          go build main.go

          mv main "../kind-bin/kind-linux-amd64"

          ls -l ../kind-bin/
  - put: kind-build
    params:
      file: kind-bin/kind-linux-amd64

- name: test with kind-master
  plan:
  - in_parallel:
    - <<: *fromDevImageBuild
      get: kind-on-c
    - <<: *fromDevImageBuild
      get: dev-image
    - &fromKindRelease
      get: kind-release
      passed: [ build kind from master ]
      resource: kind-build
      trigger: true
  - *testTask
- name: test with kind-master and k8s-1.13
  plan:
  - in_parallel:
    - <<: *fromDevImageBuild
      get: kind-on-c
    - <<: *fromDevImageBuild
      get: dev-image
    - <<: *fromKindRelease
    - get: k8s-git
      resource: k8s-git-1.13
  - << : *testTask
- name: test with kind-master and k8s-1.14
  plan:
  - in_parallel:
    - <<: *fromDevImageBuild
      get: kind-on-c
    - <<: *fromDevImageBuild
      get: dev-image
    - <<: *fromKindRelease
    - get: k8s-git
      resource: k8s-git-1.14
  - << : *testTask
- name: test with kind-master and k8s-1.15
  plan:
  - in_parallel:
    - <<: *fromDevImageBuild
      get: kind-on-c
    - <<: *fromDevImageBuild
      get: dev-image
    - <<: *fromKindRelease
    - get: k8s-git
      resource: k8s-git-1.15
  - << : *testTask
- name: test with kind-master and k8s-master
  plan:
  - in_parallel:
    - <<: *fromDevImageBuild
      get: kind-on-c
    - <<: *fromDevImageBuild
      get: dev-image
    - <<: *fromKindRelease
    - get: k8s-git
      resource: k8s-git-master
  - << : *testTask

groups:
- name: all
  jobs:
  - promote
  - build dev-image
  - test
  - test with k8s-master
  - test with k8s-1.15
  - test with k8s-1.14
  - test with k8s-1.13
  - build kind from master
  - test with kind-master
  - test with kind-master and k8s-1.13
  - test with kind-master and k8s-1.14
  - test with kind-master and k8s-1.15
  - test with kind-master and k8s-master
- name: kind from upstream
  jobs:
  - build dev-image
  - test
  - test with k8s-master
  - test with k8s-1.15
  - test with k8s-1.14
  - test with k8s-1.13
- name: kind from master
  jobs:
  - build dev-image
  - build kind from master
  - test with kind-master
  - test with kind-master and k8s-1.13
  - test with kind-master and k8s-1.14
  - test with kind-master and k8s-1.15
  - test with kind-master and k8s-master
- name: promote
  jobs:
  - promote
